// (c) EIKONA AG, it.x informationssysteme gmbh, Alle Rechte vorbehalten.
//
// Diese Datei wurde automatisch generiert, Aenderungen an dieser Datei gehen verloren.
if (typeof(Cycon) === 'undefined') Cycon = {};
Cycon.urlRoot = 'http://ffeel.de/';
if (!Cycon.System) Cycon.System = {};
Cycon.System.id = 1;
Cycon.System.Login = {};
Cycon.System.Login.login = {};
Cycon.System.Login.login.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&modul_id=' + Cycon.System.id + '&klasse=login&com=login';
if (!Cycon.System.Plugin) Cycon.System.Plugin = {};
Cycon.System.Plugin.GoogleMaps = {};
Cycon.System.Plugin.GoogleMaps.sucheOrt = {};
Cycon.System.Plugin.GoogleMaps.sucheOrt.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&modul_id=' + Cycon.System.id + '&klasse=google_maps&com=plugin_suche_ort';
if (!Cycon.Autoren) Cycon.Autoren = {};
Cycon.Autoren.id = 2;
if (!Cycon.Seiten) Cycon.Seiten = {};
Cycon.Seiten.id = 6;
if (!Cycon.Seiten.Elemente) Cycon.Seiten.Elemente = {};
Cycon.Seiten.Elemente.ElementFlash = {};
Cycon.Seiten.Elemente.ElementFlash.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=flash&element_funktion=element_flash';
Cycon.Seiten.Elemente.ElementTitel = {};
Cycon.Seiten.Elemente.ElementTitel.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_titel';
Cycon.Seiten.Elemente.ElementText = {};
Cycon.Seiten.Elemente.ElementText.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_text';
Cycon.Seiten.Elemente.ElementBild = {};
Cycon.Seiten.Elemente.ElementBild.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_bild';
Cycon.Seiten.Elemente.ElementLink = {};
Cycon.Seiten.Elemente.ElementLink.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_link';
Cycon.Seiten.Elemente.ElementLinkHref = {};
Cycon.Seiten.Elemente.ElementLinkHref.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_link_href';
Cycon.Seiten.Elemente.ElementLinkSocial = {};
Cycon.Seiten.Elemente.ElementLinkSocial.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_link_social';
Cycon.Seiten.Elemente.ElementDokument = {};
Cycon.Seiten.Elemente.ElementDokument.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_dokument';
Cycon.Seiten.Elemente.ElementAbsatz = {};
Cycon.Seiten.Elemente.ElementAbsatz.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz';
Cycon.Seiten.Elemente.ElementAbsatzFooter = {};
Cycon.Seiten.Elemente.ElementAbsatzFooter.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz_footer';
Cycon.Seiten.Elemente.ElementAbsatzMainStage = {};
Cycon.Seiten.Elemente.ElementAbsatzMainStage.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz_main_stage';
Cycon.Seiten.Elemente.ElementAbsatzAnimation = {};
Cycon.Seiten.Elemente.ElementAbsatzAnimation.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz_animation';
Cycon.Seiten.Elemente.ElementAbsatzStory = {};
Cycon.Seiten.Elemente.ElementAbsatzStory.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz_story';
Cycon.Seiten.Elemente.ElementAbsatzProduct = {};
Cycon.Seiten.Elemente.ElementAbsatzProduct.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz_product';
Cycon.Seiten.Elemente.ElementAbsatzQuestion = {};
Cycon.Seiten.Elemente.ElementAbsatzQuestion.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz_question';
Cycon.Seiten.Elemente.ElementAbsatzInstagram = {};
Cycon.Seiten.Elemente.ElementAbsatzInstagram.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_absatz_instagram';
Cycon.Seiten.Elemente.ElementContainer = {};
Cycon.Seiten.Elemente.ElementContainer.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_container';
Cycon.Seiten.Elemente.ElementContainerFooter = {};
Cycon.Seiten.Elemente.ElementContainerFooter.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_container_footer';
Cycon.Seiten.Elemente.ElementUmbruch = {};
Cycon.Seiten.Elemente.ElementUmbruch.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_umbruch';
Cycon.Seiten.Elemente.ElementTabelle = {};
Cycon.Seiten.Elemente.ElementTabelle.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_tabelle';
Cycon.Seiten.Elemente.ElementTabelleKopf = {};
Cycon.Seiten.Elemente.ElementTabelleKopf.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_tabelle_kopf';
Cycon.Seiten.Elemente.ElementTabelleZeile = {};
Cycon.Seiten.Elemente.ElementTabelleZeile.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_tabelle_zeile';
Cycon.Seiten.Elemente.ElementHtml = {};
Cycon.Seiten.Elemente.ElementHtml.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=layout&element_funktion=element_html';
Cycon.Seiten.Elemente.ElementModulBenutzer = {};
Cycon.Seiten.Elemente.ElementModulBenutzer.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_benutzer&element_funktion=element_modul_benutzer';
Cycon.Seiten.Elemente.ElementModulDownloadcenter = {};
Cycon.Seiten.Elemente.ElementModulDownloadcenter.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_downloadcenter&element_funktion=element_modul_downloadcenter';
Cycon.Seiten.Elemente.ElementVerweisDownloadcenter = {};
Cycon.Seiten.Elemente.ElementVerweisDownloadcenter.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_downloadcenter&element_funktion=element_verweis_downloadcenter';
Cycon.Seiten.Elemente.ElementModulFaqs = {};
Cycon.Seiten.Elemente.ElementModulFaqs.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_faqs&element_funktion=element_modul_faqs';
Cycon.Seiten.Elemente.ElementModulFormulargenerator = {};
Cycon.Seiten.Elemente.ElementModulFormulargenerator.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_formulargenerator&element_funktion=element_modul_formulargenerator';
Cycon.Seiten.Elemente.ElementModulGalerien = {};
Cycon.Seiten.Elemente.ElementModulGalerien.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_galerien&element_funktion=element_modul_galerien';
Cycon.Seiten.Elemente.ElementModulGlossar = {};
Cycon.Seiten.Elemente.ElementModulGlossar.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_glossar&element_funktion=element_modul_glossar';
Cycon.Seiten.Elemente.ElementModulLandkarte = {};
Cycon.Seiten.Elemente.ElementModulLandkarte.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_landkarte&element_funktion=element_modul_landkarte';
Cycon.Seiten.Elemente.ElementModulNavigation = {};
Cycon.Seiten.Elemente.ElementModulNavigation.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_navigation&element_funktion=element_modul_navigation';
Cycon.Seiten.Elemente.ElementModulNavigationSeitenOrdner = {};
Cycon.Seiten.Elemente.ElementModulNavigationSeitenOrdner.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_navigation&element_funktion=element_modul_navigation_seiten_ordner';
Cycon.Seiten.Elemente.ElementModulNews = {};
Cycon.Seiten.Elemente.ElementModulNews.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_news&element_funktion=element_modul_news';
Cycon.Seiten.Elemente.ElementModulNewsletter = {};
Cycon.Seiten.Elemente.ElementModulNewsletter.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_newsletter&element_funktion=element_modul_newsletter';
Cycon.Seiten.Elemente.ElementModulNewsletterEmpfaenger = {};
Cycon.Seiten.Elemente.ElementModulNewsletterEmpfaenger.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_newsletter&element_funktion=element_modul_newsletter_empfaenger';
Cycon.Seiten.Elemente.ElementNewsletterVerzeichnis = {};
Cycon.Seiten.Elemente.ElementNewsletterVerzeichnis.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_newsletter&element_funktion=element_newsletter_verzeichnis';
Cycon.Seiten.Elemente.ElementNewsletterZeile = {};
Cycon.Seiten.Elemente.ElementNewsletterZeile.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_newsletter&element_funktion=element_newsletter_zeile';
Cycon.Seiten.Elemente.ElementNewsletterBild = {};
Cycon.Seiten.Elemente.ElementNewsletterBild.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_newsletter&element_funktion=element_newsletter_bild';
Cycon.Seiten.Elemente.ElementNewsletterAbsatz = {};
Cycon.Seiten.Elemente.ElementNewsletterAbsatz.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_newsletter&element_funktion=element_newsletter_absatz';
Cycon.Seiten.Elemente.ElementModulSeitenFavoriten = {};
Cycon.Seiten.Elemente.ElementModulSeitenFavoriten.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_seiten_favoriten&element_funktion=element_modul_seiten_favoriten';
Cycon.Seiten.Elemente.ElementModulSprachen = {};
Cycon.Seiten.Elemente.ElementModulSprachen.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_sprachen&element_funktion=element_modul_sprachen';
Cycon.Seiten.Elemente.ElementSuche = {};
Cycon.Seiten.Elemente.ElementSuche.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_suche&element_funktion=element_suche';
Cycon.Seiten.Elemente.ElementModulSucheKategorien = {};
Cycon.Seiten.Elemente.ElementModulSucheKategorien.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_suche&element_funktion=element_modul_suche_kategorien';
Cycon.Seiten.Elemente.ElementFormularLogin = {};
Cycon.Seiten.Elemente.ElementFormularLogin.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_system&element_funktion=element_formular_login';
Cycon.Seiten.Elemente.ElementFormularPasswort = {};
Cycon.Seiten.Elemente.ElementFormularPasswort.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_system&element_funktion=element_formular_passwort';
Cycon.Seiten.Elemente.ElementModulSystemIstNeu = {};
Cycon.Seiten.Elemente.ElementModulSystemIstNeu.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_system&element_funktion=element_modul_system_ist_neu';
Cycon.Seiten.Elemente.ElementModulVerwandteInhalte = {};
Cycon.Seiten.Elemente.ElementModulVerwandteInhalte.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_verwandte_inhalte&element_funktion=element_modul_verwandte_inhalte';
Cycon.Seiten.Elemente.ElementVerwandteInhalte = {};
Cycon.Seiten.Elemente.ElementVerwandteInhalte.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_verwandte_inhalte&element_funktion=element_verwandte_inhalte';
Cycon.Seiten.Elemente.ElementModulWarenkorb = {};
Cycon.Seiten.Elemente.ElementModulWarenkorb.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=modul_warenkorb&element_funktion=element_modul_warenkorb';
Cycon.Seiten.Elemente.ElementSlider = {};
Cycon.Seiten.Elemente.ElementSlider.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=slider&element_funktion=element_slider';
Cycon.Seiten.Elemente.ElementSocialMedia = {};
Cycon.Seiten.Elemente.ElementSocialMedia.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=social_media&element_funktion=element_social_media';
Cycon.Seiten.Elemente.ElementVideo = {};
Cycon.Seiten.Elemente.ElementVideo.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=video&element_funktion=element_video';
Cycon.Seiten.Elemente.ElementVideoVimeo = {};
Cycon.Seiten.Elemente.ElementVideoVimeo.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=video&element_funktion=element_video_vimeo';
Cycon.Seiten.Elemente.ElementVideoYoutube = {};
Cycon.Seiten.Elemente.ElementVideoYoutube.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&element_datei=video&element_funktion=element_video_youtube';
if (!Cycon.Navigationen) Cycon.Navigationen = {};
Cycon.Navigationen.id = 7;
if (!Cycon.Sprachen) Cycon.Sprachen = {};
Cycon.Sprachen.id = 8;
if (!Cycon.Benutzer) Cycon.Benutzer = {};
Cycon.Benutzer.id = 15;
if (!Cycon.Newsletter) Cycon.Newsletter = {};
Cycon.Newsletter.id = 18;
if (!Cycon.Galerien) Cycon.Galerien = {};
Cycon.Galerien.id = 36;
if (!Cycon.Suche) Cycon.Suche = {};
Cycon.Suche.id = 56;
Cycon.Suche.Suche = {};
Cycon.Suche.Suche.sucheVorschlaege = {};
Cycon.Suche.Suche.sucheVorschlaege.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&modul_id=' + Cycon.Suche.id + '&klasse=suche&com=suche_vorschlaege';
if (!Cycon.Formulargenerator) Cycon.Formulargenerator = {};
Cycon.Formulargenerator.id = 57;
if (!Cycon.Landkarte) Cycon.Landkarte = {};
Cycon.Landkarte.id = 64;
Cycon.Landkarte.Landkarte = {};
Cycon.Landkarte.Landkarte.sucheOrt = {};
Cycon.Landkarte.Landkarte.sucheOrt.url = Cycon.urlRoot + 'common/ajax.php?bereich=portal&modul_id=' + Cycon.Landkarte.id + '&klasse=landkarte&com=suche_ort';
if (!Cycon.Projektaenderungen) Cycon.Projektaenderungen = {};
Cycon.Projektaenderungen.id = 99;
if (!Cycon.MODUL) Cycon.MODUL = {};
Cycon.MODUL.id = 101;
